### PR TITLE
Added support for x5c header

### PR DESCRIPTION
**Pull request by erlendfg**
This PR will make it possible to add a certificate chain as an X5C attribute.

### CODE REVIEW

**Comment by erlendfg** [comment]
This PR should be linked to the following issue, but I'm not sure how to do that:
https://github.com/gravitee-io/issues/issues/2999

**Comment by brasseld** [comment]
Hi @erlendfg 

Sorry for being late on this.

Please reword the commit message to something like this to attache to the issue:

```
feat: Added support for x5c header

Closes gravitee-io/issues#2999
```

Also, do you think it's possible to add a unit test to check certificate ?

**Comment by erlendfg** [comment]
@brasseld, I have improved the test case with certificate validation. Still one commit, because I rebased and reworded in order to add the feat type.

**Comment by brasseld** [comment]
Thanks a lot @erlendfg

**Pull request merged**
